// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanBattleReq.proto

package com.pureland.common.protocal;

public final class ClanBattleReqProtocal {
  private ClanBattleReqProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanBattleReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .ClanBattleReq.RequestType requestType = 1;
    /**
     * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
     */
    boolean hasRequestType();
    /**
     * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
     */
    com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType getRequestType();

    // repeated int64 chooseList = 2;
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    java.util.List<java.lang.Long> getChooseListList();
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    int getChooseListCount();
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    long getChooseList(int index);

    // optional .ClanBaseVO clanBaseVO = 3;
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    boolean hasClanBaseVO();
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO();
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder();

    // optional int64 operaId = 4;
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    boolean hasOperaId();
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    long getOperaId();

    // optional int32 armyId = 5;
    /**
     * <code>optional int32 armyId = 5;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    boolean hasArmyId();
    /**
     * <code>optional int32 armyId = 5;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    int getArmyId();

    // optional bytes sound = 6;
    /**
     * <code>optional bytes sound = 6;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    boolean hasSound();
    /**
     * <code>optional bytes sound = 6;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    com.google.protobuf.ByteString getSound();

    // optional .BattleResultVO battleResultVO = 7;
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    boolean hasBattleResultVO();
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO getBattleResultVO();
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder getBattleResultVOOrBuilder();

    // optional .BattleReplayVO battleReplayVO = 8;
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    boolean hasBattleReplayVO();
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO getBattleReplayVO();
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder getBattleReplayVOOrBuilder();
  }
  /**
   * Protobuf type {@code ClanBattleReq}
   */
  public static final class ClanBattleReq extends
      com.google.protobuf.GeneratedMessage
      implements ClanBattleReqOrBuilder {
    // Use ClanBattleReq.newBuilder() to construct.
    private ClanBattleReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanBattleReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanBattleReq defaultInstance;
    public static ClanBattleReq getDefaultInstance() {
      return defaultInstance;
    }

    public ClanBattleReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanBattleReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType value = com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = value;
              }
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                chooseList_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              chooseList_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                chooseList_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                chooseList_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = clanBaseVO_.toBuilder();
              }
              clanBaseVO_ = input.readMessage(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clanBaseVO_);
                clanBaseVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              operaId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              armyId_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              sound_ = input.readBytes();
              break;
            }
            case 58: {
              com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = battleResultVO_.toBuilder();
              }
              battleResultVO_ = input.readMessage(com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(battleResultVO_);
                battleResultVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 66: {
              com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = battleReplayVO_.toBuilder();
              }
              battleReplayVO_ = input.readMessage(com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(battleReplayVO_);
                battleReplayVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          chooseList_ = java.util.Collections.unmodifiableList(chooseList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.ClanBattleReqProtocal.internal_static_ClanBattleReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.ClanBattleReqProtocal.internal_static_ClanBattleReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.class, com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanBattleReq> PARSER =
        new com.google.protobuf.AbstractParser<ClanBattleReq>() {
      public ClanBattleReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanBattleReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanBattleReq> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ClanBattleReq.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ChooseBattleMember = 1;</code>
       *
       * <pre>
       *公会战开始选人
       * </pre>
       */
      ChooseBattleMember(0, 1),
      /**
       * <code>PiPei = 2;</code>
       *
       * <pre>
       *公会战开始匹配
       * </pre>
       */
      PiPei(1, 2),
      /**
       * <code>ClanBattleInfo = 3;</code>
       *
       * <pre>
       *公会战详情
       * </pre>
       */
      ClanBattleInfo(2, 3),
      /**
       * <code>ClanBattleDonate = 4;</code>
       *
       * <pre>
       *公会战捐兵
       * </pre>
       */
      ClanBattleDonate(3, 4),
      /**
       * <code>CancelPiPei = 5;</code>
       *
       * <pre>
       * 取消公会战匹配
       * </pre>
       */
      CancelPiPei(4, 5),
      /**
       * <code>ClanBattleFightBegin = 6;</code>
       *
       * <pre>
       *公会战战斗开始
       * </pre>
       */
      ClanBattleFightBegin(5, 6),
      /**
       * <code>ClanBattleFightResult = 7;</code>
       *
       * <pre>
       *公会战战斗结果
       * </pre>
       */
      ClanBattleFightResult(6, 7),
      /**
       * <code>DeleteClanBattleDonate = 8;</code>
       *
       * <pre>
       *删除捐献
       * </pre>
       */
      DeleteClanBattleDonate(7, 8),
      /**
       * <code>QueryClanBattleMemberInfo = 9;</code>
       */
      QueryClanBattleMemberInfo(8, 9),
      /**
       * <code>ClanBattleTrueFightBegin = 10;</code>
       *
       * <pre>
       *公会战战斗真正开始
       * </pre>
       */
      ClanBattleTrueFightBegin(9, 10),
      /**
       * <code>ClanBattleStatisticsInfo = 11;</code>
       *
       * <pre>
       *公会战统计
       * </pre>
       */
      ClanBattleStatisticsInfo(10, 11),
      /**
       * <code>ClanBattleHistory = 12;</code>
       *
       * <pre>
       *公会战历史
       * </pre>
       */
      ClanBattleHistory(11, 12),
      ;

      /**
       * <code>ChooseBattleMember = 1;</code>
       *
       * <pre>
       *公会战开始选人
       * </pre>
       */
      public static final int ChooseBattleMember_VALUE = 1;
      /**
       * <code>PiPei = 2;</code>
       *
       * <pre>
       *公会战开始匹配
       * </pre>
       */
      public static final int PiPei_VALUE = 2;
      /**
       * <code>ClanBattleInfo = 3;</code>
       *
       * <pre>
       *公会战详情
       * </pre>
       */
      public static final int ClanBattleInfo_VALUE = 3;
      /**
       * <code>ClanBattleDonate = 4;</code>
       *
       * <pre>
       *公会战捐兵
       * </pre>
       */
      public static final int ClanBattleDonate_VALUE = 4;
      /**
       * <code>CancelPiPei = 5;</code>
       *
       * <pre>
       * 取消公会战匹配
       * </pre>
       */
      public static final int CancelPiPei_VALUE = 5;
      /**
       * <code>ClanBattleFightBegin = 6;</code>
       *
       * <pre>
       *公会战战斗开始
       * </pre>
       */
      public static final int ClanBattleFightBegin_VALUE = 6;
      /**
       * <code>ClanBattleFightResult = 7;</code>
       *
       * <pre>
       *公会战战斗结果
       * </pre>
       */
      public static final int ClanBattleFightResult_VALUE = 7;
      /**
       * <code>DeleteClanBattleDonate = 8;</code>
       *
       * <pre>
       *删除捐献
       * </pre>
       */
      public static final int DeleteClanBattleDonate_VALUE = 8;
      /**
       * <code>QueryClanBattleMemberInfo = 9;</code>
       */
      public static final int QueryClanBattleMemberInfo_VALUE = 9;
      /**
       * <code>ClanBattleTrueFightBegin = 10;</code>
       *
       * <pre>
       *公会战战斗真正开始
       * </pre>
       */
      public static final int ClanBattleTrueFightBegin_VALUE = 10;
      /**
       * <code>ClanBattleStatisticsInfo = 11;</code>
       *
       * <pre>
       *公会战统计
       * </pre>
       */
      public static final int ClanBattleStatisticsInfo_VALUE = 11;
      /**
       * <code>ClanBattleHistory = 12;</code>
       *
       * <pre>
       *公会战历史
       * </pre>
       */
      public static final int ClanBattleHistory_VALUE = 12;


      public final int getNumber() { return value; }

      public static RequestType valueOf(int value) {
        switch (value) {
          case 1: return ChooseBattleMember;
          case 2: return PiPei;
          case 3: return ClanBattleInfo;
          case 4: return ClanBattleDonate;
          case 5: return CancelPiPei;
          case 6: return ClanBattleFightBegin;
          case 7: return ClanBattleFightResult;
          case 8: return DeleteClanBattleDonate;
          case 9: return QueryClanBattleMemberInfo;
          case 10: return ClanBattleTrueFightBegin;
          case 11: return ClanBattleStatisticsInfo;
          case 12: return ClanBattleHistory;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClanBattleReq.RequestType)
    }

    private int bitField0_;
    // required .ClanBattleReq.RequestType requestType = 1;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType requestType_;
    /**
     * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
     */
    public com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType getRequestType() {
      return requestType_;
    }

    // repeated int64 chooseList = 2;
    public static final int CHOOSELIST_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> chooseList_;
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getChooseListList() {
      return chooseList_;
    }
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    public int getChooseListCount() {
      return chooseList_.size();
    }
    /**
     * <code>repeated int64 chooseList = 2;</code>
     */
    public long getChooseList(int index) {
      return chooseList_.get(index);
    }

    // optional .ClanBaseVO clanBaseVO = 3;
    public static final int CLANBASEVO_FIELD_NUMBER = 3;
    private com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO clanBaseVO_;
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public boolean hasClanBaseVO() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO() {
      return clanBaseVO_;
    }
    /**
     * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
     *
     * <pre>
     *公会基础信息
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder() {
      return clanBaseVO_;
    }

    // optional int64 operaId = 4;
    public static final int OPERAID_FIELD_NUMBER = 4;
    private long operaId_;
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    public boolean hasOperaId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 operaId = 4;</code>
     *
     * <pre>
     *被操作的pid
     * </pre>
     */
    public long getOperaId() {
      return operaId_;
    }

    // optional int32 armyId = 5;
    public static final int ARMYID_FIELD_NUMBER = 5;
    private int armyId_;
    /**
     * <code>optional int32 armyId = 5;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    public boolean hasArmyId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 armyId = 5;</code>
     *
     * <pre>
     *增援的军队
     * </pre>
     */
    public int getArmyId() {
      return armyId_;
    }

    // optional bytes sound = 6;
    public static final int SOUND_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString sound_;
    /**
     * <code>optional bytes sound = 6;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    public boolean hasSound() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes sound = 6;</code>
     *
     * <pre>
     *语音
     * </pre>
     */
    public com.google.protobuf.ByteString getSound() {
      return sound_;
    }

    // optional .BattleResultVO battleResultVO = 7;
    public static final int BATTLERESULTVO_FIELD_NUMBER = 7;
    private com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO battleResultVO_;
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    public boolean hasBattleResultVO() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    public com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO getBattleResultVO() {
      return battleResultVO_;
    }
    /**
     * <code>optional .BattleResultVO battleResultVO = 7;</code>
     */
    public com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder getBattleResultVOOrBuilder() {
      return battleResultVO_;
    }

    // optional .BattleReplayVO battleReplayVO = 8;
    public static final int BATTLEREPLAYVO_FIELD_NUMBER = 8;
    private com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO battleReplayVO_;
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    public boolean hasBattleReplayVO() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    public com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO getBattleReplayVO() {
      return battleReplayVO_;
    }
    /**
     * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
     */
    public com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder getBattleReplayVOOrBuilder() {
      return battleReplayVO_;
    }

    private void initFields() {
      requestType_ = com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType.ChooseBattleMember;
      chooseList_ = java.util.Collections.emptyList();
      clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
      operaId_ = 0L;
      armyId_ = 0;
      sound_ = com.google.protobuf.ByteString.EMPTY;
      battleResultVO_ = com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.getDefaultInstance();
      battleReplayVO_ = com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasBattleResultVO()) {
        if (!getBattleResultVO().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBattleReplayVO()) {
        if (!getBattleReplayVO().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_.getNumber());
      }
      for (int i = 0; i < chooseList_.size(); i++) {
        output.writeInt64(2, chooseList_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, clanBaseVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, operaId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, armyId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, sound_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, battleResultVO_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(8, battleReplayVO_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < chooseList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(chooseList_.get(i));
        }
        size += dataSize;
        size += 1 * getChooseListList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, clanBaseVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, operaId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, armyId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, sound_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, battleResultVO_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, battleReplayVO_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanBattleReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.ClanBattleReqProtocal.internal_static_ClanBattleReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.ClanBattleReqProtocal.internal_static_ClanBattleReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.class, com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.Builder.class);
      }

      // Construct using com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClanBaseVOFieldBuilder();
          getBattleResultVOFieldBuilder();
          getBattleReplayVOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestType_ = com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType.ChooseBattleMember;
        bitField0_ = (bitField0_ & ~0x00000001);
        chooseList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
        } else {
          clanBaseVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        operaId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        armyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sound_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (battleResultVOBuilder_ == null) {
          battleResultVO_ = com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.getDefaultInstance();
        } else {
          battleResultVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (battleReplayVOBuilder_ == null) {
          battleReplayVO_ = com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.getDefaultInstance();
        } else {
          battleReplayVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.ClanBattleReqProtocal.internal_static_ClanBattleReq_descriptor;
      }

      public com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq getDefaultInstanceForType() {
        return com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.getDefaultInstance();
      }

      public com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq build() {
        com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq buildPartial() {
        com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq result = new com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          chooseList_ = java.util.Collections.unmodifiableList(chooseList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.chooseList_ = chooseList_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (clanBaseVOBuilder_ == null) {
          result.clanBaseVO_ = clanBaseVO_;
        } else {
          result.clanBaseVO_ = clanBaseVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.operaId_ = operaId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.armyId_ = armyId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sound_ = sound_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (battleResultVOBuilder_ == null) {
          result.battleResultVO_ = battleResultVO_;
        } else {
          result.battleResultVO_ = battleResultVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        if (battleReplayVOBuilder_ == null) {
          result.battleReplayVO_ = battleReplayVO_;
        } else {
          result.battleReplayVO_ = battleReplayVOBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq) {
          return mergeFrom((com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq other) {
        if (other == com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (!other.chooseList_.isEmpty()) {
          if (chooseList_.isEmpty()) {
            chooseList_ = other.chooseList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChooseListIsMutable();
            chooseList_.addAll(other.chooseList_);
          }
          onChanged();
        }
        if (other.hasClanBaseVO()) {
          mergeClanBaseVO(other.getClanBaseVO());
        }
        if (other.hasOperaId()) {
          setOperaId(other.getOperaId());
        }
        if (other.hasArmyId()) {
          setArmyId(other.getArmyId());
        }
        if (other.hasSound()) {
          setSound(other.getSound());
        }
        if (other.hasBattleResultVO()) {
          mergeBattleResultVO(other.getBattleResultVO());
        }
        if (other.hasBattleReplayVO()) {
          mergeBattleReplayVO(other.getBattleReplayVO());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          
          return false;
        }
        if (hasBattleResultVO()) {
          if (!getBattleResultVO().isInitialized()) {
            
            return false;
          }
        }
        if (hasBattleReplayVO()) {
          if (!getBattleReplayVO().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .ClanBattleReq.RequestType requestType = 1;
      private com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType requestType_ = com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType.ChooseBattleMember;
      /**
       * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
       */
      public com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType getRequestType() {
        return requestType_;
      }
      /**
       * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
       */
      public Builder setRequestType(com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ClanBattleReq.RequestType requestType = 1;</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = com.pureland.common.protocal.ClanBattleReqProtocal.ClanBattleReq.RequestType.ChooseBattleMember;
        onChanged();
        return this;
      }

      // repeated int64 chooseList = 2;
      private java.util.List<java.lang.Long> chooseList_ = java.util.Collections.emptyList();
      private void ensureChooseListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          chooseList_ = new java.util.ArrayList<java.lang.Long>(chooseList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getChooseListList() {
        return java.util.Collections.unmodifiableList(chooseList_);
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public int getChooseListCount() {
        return chooseList_.size();
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public long getChooseList(int index) {
        return chooseList_.get(index);
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public Builder setChooseList(
          int index, long value) {
        ensureChooseListIsMutable();
        chooseList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public Builder addChooseList(long value) {
        ensureChooseListIsMutable();
        chooseList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public Builder addAllChooseList(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureChooseListIsMutable();
        super.addAll(values, chooseList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 chooseList = 2;</code>
       */
      public Builder clearChooseList() {
        chooseList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional .ClanBaseVO clanBaseVO = 3;
      private com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder> clanBaseVOBuilder_;
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public boolean hasClanBaseVO() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO getClanBaseVO() {
        if (clanBaseVOBuilder_ == null) {
          return clanBaseVO_;
        } else {
          return clanBaseVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder setClanBaseVO(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO value) {
        if (clanBaseVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clanBaseVO_ = value;
          onChanged();
        } else {
          clanBaseVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder setClanBaseVO(
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder builderForValue) {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = builderForValue.build();
          onChanged();
        } else {
          clanBaseVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder mergeClanBaseVO(com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO value) {
        if (clanBaseVOBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              clanBaseVO_ != com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance()) {
            clanBaseVO_ =
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.newBuilder(clanBaseVO_).mergeFrom(value).buildPartial();
          } else {
            clanBaseVO_ = value;
          }
          onChanged();
        } else {
          clanBaseVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public Builder clearClanBaseVO() {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVO_ = com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.getDefaultInstance();
          onChanged();
        } else {
          clanBaseVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder getClanBaseVOBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getClanBaseVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder getClanBaseVOOrBuilder() {
        if (clanBaseVOBuilder_ != null) {
          return clanBaseVOBuilder_.getMessageOrBuilder();
        } else {
          return clanBaseVO_;
        }
      }
      /**
       * <code>optional .ClanBaseVO clanBaseVO = 3;</code>
       *
       * <pre>
       *公会基础信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder> 
          getClanBaseVOFieldBuilder() {
        if (clanBaseVOBuilder_ == null) {
          clanBaseVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVO.Builder, com.pureland.common.protocal.vo.ClanBaseVOProtocal.ClanBaseVOOrBuilder>(
                  clanBaseVO_,
                  getParentForChildren(),
                  isClean());
          clanBaseVO_ = null;
        }
        return clanBaseVOBuilder_;
      }

      // optional int64 operaId = 4;
      private long operaId_ ;
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public boolean hasOperaId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public long getOperaId() {
        return operaId_;
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public Builder setOperaId(long value) {
        bitField0_ |= 0x00000008;
        operaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 operaId = 4;</code>
       *
       * <pre>
       *被操作的pid
       * </pre>
       */
      public Builder clearOperaId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operaId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 armyId = 5;
      private int armyId_ ;
      /**
       * <code>optional int32 armyId = 5;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public boolean hasArmyId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 armyId = 5;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public int getArmyId() {
        return armyId_;
      }
      /**
       * <code>optional int32 armyId = 5;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public Builder setArmyId(int value) {
        bitField0_ |= 0x00000010;
        armyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 armyId = 5;</code>
       *
       * <pre>
       *增援的军队
       * </pre>
       */
      public Builder clearArmyId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        armyId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes sound = 6;
      private com.google.protobuf.ByteString sound_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sound = 6;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public boolean hasSound() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes sound = 6;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public com.google.protobuf.ByteString getSound() {
        return sound_;
      }
      /**
       * <code>optional bytes sound = 6;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public Builder setSound(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sound = 6;</code>
       *
       * <pre>
       *语音
       * </pre>
       */
      public Builder clearSound() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sound_ = getDefaultInstance().getSound();
        onChanged();
        return this;
      }

      // optional .BattleResultVO battleResultVO = 7;
      private com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO battleResultVO_ = com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder> battleResultVOBuilder_;
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public boolean hasBattleResultVO() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO getBattleResultVO() {
        if (battleResultVOBuilder_ == null) {
          return battleResultVO_;
        } else {
          return battleResultVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public Builder setBattleResultVO(com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO value) {
        if (battleResultVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          battleResultVO_ = value;
          onChanged();
        } else {
          battleResultVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public Builder setBattleResultVO(
          com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder builderForValue) {
        if (battleResultVOBuilder_ == null) {
          battleResultVO_ = builderForValue.build();
          onChanged();
        } else {
          battleResultVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public Builder mergeBattleResultVO(com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO value) {
        if (battleResultVOBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              battleResultVO_ != com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.getDefaultInstance()) {
            battleResultVO_ =
              com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.newBuilder(battleResultVO_).mergeFrom(value).buildPartial();
          } else {
            battleResultVO_ = value;
          }
          onChanged();
        } else {
          battleResultVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public Builder clearBattleResultVO() {
        if (battleResultVOBuilder_ == null) {
          battleResultVO_ = com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.getDefaultInstance();
          onChanged();
        } else {
          battleResultVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder getBattleResultVOBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getBattleResultVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      public com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder getBattleResultVOOrBuilder() {
        if (battleResultVOBuilder_ != null) {
          return battleResultVOBuilder_.getMessageOrBuilder();
        } else {
          return battleResultVO_;
        }
      }
      /**
       * <code>optional .BattleResultVO battleResultVO = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder> 
          getBattleResultVOFieldBuilder() {
        if (battleResultVOBuilder_ == null) {
          battleResultVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVO.Builder, com.pureland.common.protocal.vo.BattleResultVOProtocal.BattleResultVOOrBuilder>(
                  battleResultVO_,
                  getParentForChildren(),
                  isClean());
          battleResultVO_ = null;
        }
        return battleResultVOBuilder_;
      }

      // optional .BattleReplayVO battleReplayVO = 8;
      private com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO battleReplayVO_ = com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder> battleReplayVOBuilder_;
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public boolean hasBattleReplayVO() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO getBattleReplayVO() {
        if (battleReplayVOBuilder_ == null) {
          return battleReplayVO_;
        } else {
          return battleReplayVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public Builder setBattleReplayVO(com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO value) {
        if (battleReplayVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          battleReplayVO_ = value;
          onChanged();
        } else {
          battleReplayVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public Builder setBattleReplayVO(
          com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder builderForValue) {
        if (battleReplayVOBuilder_ == null) {
          battleReplayVO_ = builderForValue.build();
          onChanged();
        } else {
          battleReplayVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public Builder mergeBattleReplayVO(com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO value) {
        if (battleReplayVOBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              battleReplayVO_ != com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.getDefaultInstance()) {
            battleReplayVO_ =
              com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.newBuilder(battleReplayVO_).mergeFrom(value).buildPartial();
          } else {
            battleReplayVO_ = value;
          }
          onChanged();
        } else {
          battleReplayVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public Builder clearBattleReplayVO() {
        if (battleReplayVOBuilder_ == null) {
          battleReplayVO_ = com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.getDefaultInstance();
          onChanged();
        } else {
          battleReplayVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder getBattleReplayVOBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getBattleReplayVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      public com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder getBattleReplayVOOrBuilder() {
        if (battleReplayVOBuilder_ != null) {
          return battleReplayVOBuilder_.getMessageOrBuilder();
        } else {
          return battleReplayVO_;
        }
      }
      /**
       * <code>optional .BattleReplayVO battleReplayVO = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder> 
          getBattleReplayVOFieldBuilder() {
        if (battleReplayVOBuilder_ == null) {
          battleReplayVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVO.Builder, com.pureland.common.protocal.vo.BattleReplayVOProtocal.BattleReplayVOOrBuilder>(
                  battleReplayVO_,
                  getParentForChildren(),
                  isClean());
          battleReplayVO_ = null;
        }
        return battleReplayVOBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClanBattleReq)
    }

    static {
      defaultInstance = new ClanBattleReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanBattleReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanBattleReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanBattleReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClanBattleReq.proto\032\020ClanBaseVO.proto\032" +
      "\024BattleResultVO.proto\032\024BattleReplayVO.pr" +
      "oto\"\250\004\n\rClanBattleReq\022/\n\013requestType\030\001 \002" +
      "(\0162\032.ClanBattleReq.RequestType\022\022\n\nchoose" +
      "List\030\002 \003(\003\022\037\n\nclanBaseVO\030\003 \001(\0132\013.ClanBas" +
      "eVO\022\017\n\007operaId\030\004 \001(\003\022\016\n\006armyId\030\005 \001(\005\022\r\n\005" +
      "sound\030\006 \001(\014\022\'\n\016battleResultVO\030\007 \001(\0132\017.Ba" +
      "ttleResultVO\022\'\n\016battleReplayVO\030\010 \001(\0132\017.B" +
      "attleReplayVO\"\256\002\n\013RequestType\022\026\n\022ChooseB" +
      "attleMember\020\001\022\t\n\005PiPei\020\002\022\022\n\016ClanBattleIn",
      "fo\020\003\022\024\n\020ClanBattleDonate\020\004\022\017\n\013CancelPiPe" +
      "i\020\005\022\030\n\024ClanBattleFightBegin\020\006\022\031\n\025ClanBat" +
      "tleFightResult\020\007\022\032\n\026DeleteClanBattleDona" +
      "te\020\010\022\035\n\031QueryClanBattleMemberInfo\020\t\022\034\n\030C" +
      "lanBattleTrueFightBegin\020\n\022\034\n\030ClanBattleS" +
      "tatisticsInfo\020\013\022\025\n\021ClanBattleHistory\020\014B5" +
      "\n\034com.pureland.common.protocalB\025ClanBatt" +
      "leReqProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanBattleReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanBattleReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanBattleReq_descriptor,
              new java.lang.String[] { "RequestType", "ChooseList", "ClanBaseVO", "OperaId", "ArmyId", "Sound", "BattleResultVO", "BattleReplayVO", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ClanBaseVOProtocal.getDescriptor(),
          com.pureland.common.protocal.vo.BattleResultVOProtocal.getDescriptor(),
          com.pureland.common.protocal.vo.BattleReplayVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
