// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FormationResp.proto

package com.pureland.common.protocal;

public final class FormationRespProtocal {
  private FormationRespProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FormationRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .FormationVO allBuildings = 1;
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    boolean hasAllBuildings();
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getAllBuildings();
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getAllBuildingsOrBuilder();

    // repeated .FormationVO formations = 2;
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> 
        getFormationsList();
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getFormations(int index);
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    int getFormationsCount();
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> 
        getFormationsOrBuilderList();
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getFormationsOrBuilder(
        int index);

    // optional int32 clanFormationId = 3;
    /**
     * <code>optional int32 clanFormationId = 3;</code>
     */
    boolean hasClanFormationId();
    /**
     * <code>optional int32 clanFormationId = 3;</code>
     */
    int getClanFormationId();

    // optional int32 personalFormationId = 4;
    /**
     * <code>optional int32 personalFormationId = 4;</code>
     */
    boolean hasPersonalFormationId();
    /**
     * <code>optional int32 personalFormationId = 4;</code>
     */
    int getPersonalFormationId();
  }
  /**
   * Protobuf type {@code FormationResp}
   */
  public static final class FormationResp extends
      com.google.protobuf.GeneratedMessage
      implements FormationRespOrBuilder {
    // Use FormationResp.newBuilder() to construct.
    private FormationResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FormationResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FormationResp defaultInstance;
    public static FormationResp getDefaultInstance() {
      return defaultInstance;
    }

    public FormationResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FormationResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = allBuildings_.toBuilder();
              }
              allBuildings_ = input.readMessage(com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(allBuildings_);
                allBuildings_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                formations_ = new java.util.ArrayList<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO>();
                mutable_bitField0_ |= 0x00000002;
              }
              formations_.add(input.readMessage(com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              clanFormationId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              personalFormationId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          formations_ = java.util.Collections.unmodifiableList(formations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.FormationRespProtocal.internal_static_FormationResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.FormationRespProtocal.internal_static_FormationResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.FormationRespProtocal.FormationResp.class, com.pureland.common.protocal.FormationRespProtocal.FormationResp.Builder.class);
    }

    public static com.google.protobuf.Parser<FormationResp> PARSER =
        new com.google.protobuf.AbstractParser<FormationResp>() {
      public FormationResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FormationResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FormationResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .FormationVO allBuildings = 1;
    public static final int ALLBUILDINGS_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO allBuildings_;
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    public boolean hasAllBuildings() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getAllBuildings() {
      return allBuildings_;
    }
    /**
     * <code>optional .FormationVO allBuildings = 1;</code>
     */
    public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getAllBuildingsOrBuilder() {
      return allBuildings_;
    }

    // repeated .FormationVO formations = 2;
    public static final int FORMATIONS_FIELD_NUMBER = 2;
    private java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> formations_;
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    public java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> getFormationsList() {
      return formations_;
    }
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> 
        getFormationsOrBuilderList() {
      return formations_;
    }
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    public int getFormationsCount() {
      return formations_.size();
    }
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getFormations(int index) {
      return formations_.get(index);
    }
    /**
     * <code>repeated .FormationVO formations = 2;</code>
     */
    public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getFormationsOrBuilder(
        int index) {
      return formations_.get(index);
    }

    // optional int32 clanFormationId = 3;
    public static final int CLANFORMATIONID_FIELD_NUMBER = 3;
    private int clanFormationId_;
    /**
     * <code>optional int32 clanFormationId = 3;</code>
     */
    public boolean hasClanFormationId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 clanFormationId = 3;</code>
     */
    public int getClanFormationId() {
      return clanFormationId_;
    }

    // optional int32 personalFormationId = 4;
    public static final int PERSONALFORMATIONID_FIELD_NUMBER = 4;
    private int personalFormationId_;
    /**
     * <code>optional int32 personalFormationId = 4;</code>
     */
    public boolean hasPersonalFormationId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 personalFormationId = 4;</code>
     */
    public int getPersonalFormationId() {
      return personalFormationId_;
    }

    private void initFields() {
      allBuildings_ = com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance();
      formations_ = java.util.Collections.emptyList();
      clanFormationId_ = 0;
      personalFormationId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasAllBuildings()) {
        if (!getAllBuildings().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFormationsCount(); i++) {
        if (!getFormations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, allBuildings_);
      }
      for (int i = 0; i < formations_.size(); i++) {
        output.writeMessage(2, formations_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, clanFormationId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, personalFormationId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allBuildings_);
      }
      for (int i = 0; i < formations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, formations_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clanFormationId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, personalFormationId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.FormationRespProtocal.FormationResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.FormationRespProtocal.FormationResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FormationResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.FormationRespProtocal.FormationRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.FormationRespProtocal.internal_static_FormationResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.FormationRespProtocal.internal_static_FormationResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.FormationRespProtocal.FormationResp.class, com.pureland.common.protocal.FormationRespProtocal.FormationResp.Builder.class);
      }

      // Construct using com.pureland.common.protocal.FormationRespProtocal.FormationResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAllBuildingsFieldBuilder();
          getFormationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (allBuildingsBuilder_ == null) {
          allBuildings_ = com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance();
        } else {
          allBuildingsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (formationsBuilder_ == null) {
          formations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          formationsBuilder_.clear();
        }
        clanFormationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        personalFormationId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.FormationRespProtocal.internal_static_FormationResp_descriptor;
      }

      public com.pureland.common.protocal.FormationRespProtocal.FormationResp getDefaultInstanceForType() {
        return com.pureland.common.protocal.FormationRespProtocal.FormationResp.getDefaultInstance();
      }

      public com.pureland.common.protocal.FormationRespProtocal.FormationResp build() {
        com.pureland.common.protocal.FormationRespProtocal.FormationResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.FormationRespProtocal.FormationResp buildPartial() {
        com.pureland.common.protocal.FormationRespProtocal.FormationResp result = new com.pureland.common.protocal.FormationRespProtocal.FormationResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (allBuildingsBuilder_ == null) {
          result.allBuildings_ = allBuildings_;
        } else {
          result.allBuildings_ = allBuildingsBuilder_.build();
        }
        if (formationsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            formations_ = java.util.Collections.unmodifiableList(formations_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.formations_ = formations_;
        } else {
          result.formations_ = formationsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clanFormationId_ = clanFormationId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.personalFormationId_ = personalFormationId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.FormationRespProtocal.FormationResp) {
          return mergeFrom((com.pureland.common.protocal.FormationRespProtocal.FormationResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.FormationRespProtocal.FormationResp other) {
        if (other == com.pureland.common.protocal.FormationRespProtocal.FormationResp.getDefaultInstance()) return this;
        if (other.hasAllBuildings()) {
          mergeAllBuildings(other.getAllBuildings());
        }
        if (formationsBuilder_ == null) {
          if (!other.formations_.isEmpty()) {
            if (formations_.isEmpty()) {
              formations_ = other.formations_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFormationsIsMutable();
              formations_.addAll(other.formations_);
            }
            onChanged();
          }
        } else {
          if (!other.formations_.isEmpty()) {
            if (formationsBuilder_.isEmpty()) {
              formationsBuilder_.dispose();
              formationsBuilder_ = null;
              formations_ = other.formations_;
              bitField0_ = (bitField0_ & ~0x00000002);
              formationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFormationsFieldBuilder() : null;
            } else {
              formationsBuilder_.addAllMessages(other.formations_);
            }
          }
        }
        if (other.hasClanFormationId()) {
          setClanFormationId(other.getClanFormationId());
        }
        if (other.hasPersonalFormationId()) {
          setPersonalFormationId(other.getPersonalFormationId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasAllBuildings()) {
          if (!getAllBuildings().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getFormationsCount(); i++) {
          if (!getFormations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.FormationRespProtocal.FormationResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.FormationRespProtocal.FormationResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .FormationVO allBuildings = 1;
      private com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO allBuildings_ = com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> allBuildingsBuilder_;
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public boolean hasAllBuildings() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getAllBuildings() {
        if (allBuildingsBuilder_ == null) {
          return allBuildings_;
        } else {
          return allBuildingsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public Builder setAllBuildings(com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO value) {
        if (allBuildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          allBuildings_ = value;
          onChanged();
        } else {
          allBuildingsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public Builder setAllBuildings(
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder builderForValue) {
        if (allBuildingsBuilder_ == null) {
          allBuildings_ = builderForValue.build();
          onChanged();
        } else {
          allBuildingsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public Builder mergeAllBuildings(com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO value) {
        if (allBuildingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              allBuildings_ != com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance()) {
            allBuildings_ =
              com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.newBuilder(allBuildings_).mergeFrom(value).buildPartial();
          } else {
            allBuildings_ = value;
          }
          onChanged();
        } else {
          allBuildingsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public Builder clearAllBuildings() {
        if (allBuildingsBuilder_ == null) {
          allBuildings_ = com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance();
          onChanged();
        } else {
          allBuildingsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder getAllBuildingsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAllBuildingsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getAllBuildingsOrBuilder() {
        if (allBuildingsBuilder_ != null) {
          return allBuildingsBuilder_.getMessageOrBuilder();
        } else {
          return allBuildings_;
        }
      }
      /**
       * <code>optional .FormationVO allBuildings = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> 
          getAllBuildingsFieldBuilder() {
        if (allBuildingsBuilder_ == null) {
          allBuildingsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder>(
                  allBuildings_,
                  getParentForChildren(),
                  isClean());
          allBuildings_ = null;
        }
        return allBuildingsBuilder_;
      }

      // repeated .FormationVO formations = 2;
      private java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> formations_ =
        java.util.Collections.emptyList();
      private void ensureFormationsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          formations_ = new java.util.ArrayList<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO>(formations_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> formationsBuilder_;

      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> getFormationsList() {
        if (formationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(formations_);
        } else {
          return formationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public int getFormationsCount() {
        if (formationsBuilder_ == null) {
          return formations_.size();
        } else {
          return formationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO getFormations(int index) {
        if (formationsBuilder_ == null) {
          return formations_.get(index);
        } else {
          return formationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder setFormations(
          int index, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO value) {
        if (formationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationsIsMutable();
          formations_.set(index, value);
          onChanged();
        } else {
          formationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder setFormations(
          int index, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder builderForValue) {
        if (formationsBuilder_ == null) {
          ensureFormationsIsMutable();
          formations_.set(index, builderForValue.build());
          onChanged();
        } else {
          formationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder addFormations(com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO value) {
        if (formationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationsIsMutable();
          formations_.add(value);
          onChanged();
        } else {
          formationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder addFormations(
          int index, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO value) {
        if (formationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationsIsMutable();
          formations_.add(index, value);
          onChanged();
        } else {
          formationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder addFormations(
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder builderForValue) {
        if (formationsBuilder_ == null) {
          ensureFormationsIsMutable();
          formations_.add(builderForValue.build());
          onChanged();
        } else {
          formationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder addFormations(
          int index, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder builderForValue) {
        if (formationsBuilder_ == null) {
          ensureFormationsIsMutable();
          formations_.add(index, builderForValue.build());
          onChanged();
        } else {
          formationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder addAllFormations(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO> values) {
        if (formationsBuilder_ == null) {
          ensureFormationsIsMutable();
          super.addAll(values, formations_);
          onChanged();
        } else {
          formationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder clearFormations() {
        if (formationsBuilder_ == null) {
          formations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          formationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public Builder removeFormations(int index) {
        if (formationsBuilder_ == null) {
          ensureFormationsIsMutable();
          formations_.remove(index);
          onChanged();
        } else {
          formationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder getFormationsBuilder(
          int index) {
        return getFormationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder getFormationsOrBuilder(
          int index) {
        if (formationsBuilder_ == null) {
          return formations_.get(index);  } else {
          return formationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> 
           getFormationsOrBuilderList() {
        if (formationsBuilder_ != null) {
          return formationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(formations_);
        }
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder addFormationsBuilder() {
        return getFormationsFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance());
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder addFormationsBuilder(
          int index) {
        return getFormationsFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.getDefaultInstance());
      }
      /**
       * <code>repeated .FormationVO formations = 2;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder> 
           getFormationsBuilderList() {
        return getFormationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder> 
          getFormationsFieldBuilder() {
        if (formationsBuilder_ == null) {
          formationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVO.Builder, com.pureland.common.protocal.vo.FormationVOProtocal.FormationVOOrBuilder>(
                  formations_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          formations_ = null;
        }
        return formationsBuilder_;
      }

      // optional int32 clanFormationId = 3;
      private int clanFormationId_ ;
      /**
       * <code>optional int32 clanFormationId = 3;</code>
       */
      public boolean hasClanFormationId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 clanFormationId = 3;</code>
       */
      public int getClanFormationId() {
        return clanFormationId_;
      }
      /**
       * <code>optional int32 clanFormationId = 3;</code>
       */
      public Builder setClanFormationId(int value) {
        bitField0_ |= 0x00000004;
        clanFormationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clanFormationId = 3;</code>
       */
      public Builder clearClanFormationId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clanFormationId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 personalFormationId = 4;
      private int personalFormationId_ ;
      /**
       * <code>optional int32 personalFormationId = 4;</code>
       */
      public boolean hasPersonalFormationId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 personalFormationId = 4;</code>
       */
      public int getPersonalFormationId() {
        return personalFormationId_;
      }
      /**
       * <code>optional int32 personalFormationId = 4;</code>
       */
      public Builder setPersonalFormationId(int value) {
        bitField0_ |= 0x00000008;
        personalFormationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 personalFormationId = 4;</code>
       */
      public Builder clearPersonalFormationId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        personalFormationId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FormationResp)
    }

    static {
      defaultInstance = new FormationResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FormationResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FormationResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FormationResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FormationResp.proto\032\021FormationVO.proto" +
      "\"\213\001\n\rFormationResp\022\"\n\014allBuildings\030\001 \001(\013" +
      "2\014.FormationVO\022 \n\nformations\030\002 \003(\0132\014.For" +
      "mationVO\022\027\n\017clanFormationId\030\003 \001(\005\022\033\n\023per" +
      "sonalFormationId\030\004 \001(\005B5\n\034com.pureland.c" +
      "ommon.protocalB\025FormationRespProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FormationResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FormationResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FormationResp_descriptor,
              new java.lang.String[] { "AllBuildings", "Formations", "ClanFormationId", "PersonalFormationId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.FormationVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
