// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GMSaveFormation.proto

package com.pureland.common.protocal;

public final class GMSaveFormationProtocal {
  private GMSaveFormationProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GMSaveFormationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .BuildingVO buildings = 1;
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> 
        getBuildingsList();
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO getBuildings(int index);
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    int getBuildingsCount();
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder> 
        getBuildingsOrBuilderList();
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder getBuildingsOrBuilder(
        int index);

    // optional bytes pngData = 2;
    /**
     * <code>optional bytes pngData = 2;</code>
     */
    boolean hasPngData();
    /**
     * <code>optional bytes pngData = 2;</code>
     */
    com.google.protobuf.ByteString getPngData();
  }
  /**
   * Protobuf type {@code GMSaveFormation}
   */
  public static final class GMSaveFormation extends
      com.google.protobuf.GeneratedMessage
      implements GMSaveFormationOrBuilder {
    // Use GMSaveFormation.newBuilder() to construct.
    private GMSaveFormation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GMSaveFormation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GMSaveFormation defaultInstance;
    public static GMSaveFormation getDefaultInstance() {
      return defaultInstance;
    }

    public GMSaveFormation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GMSaveFormation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                buildings_ = new java.util.ArrayList<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO>();
                mutable_bitField0_ |= 0x00000001;
              }
              buildings_.add(input.readMessage(com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              pngData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          buildings_ = java.util.Collections.unmodifiableList(buildings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.GMSaveFormationProtocal.internal_static_GMSaveFormation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.GMSaveFormationProtocal.internal_static_GMSaveFormation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.class, com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.Builder.class);
    }

    public static com.google.protobuf.Parser<GMSaveFormation> PARSER =
        new com.google.protobuf.AbstractParser<GMSaveFormation>() {
      public GMSaveFormation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GMSaveFormation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GMSaveFormation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .BuildingVO buildings = 1;
    public static final int BUILDINGS_FIELD_NUMBER = 1;
    private java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> buildings_;
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    public java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> getBuildingsList() {
      return buildings_;
    }
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder> 
        getBuildingsOrBuilderList() {
      return buildings_;
    }
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    public int getBuildingsCount() {
      return buildings_.size();
    }
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO getBuildings(int index) {
      return buildings_.get(index);
    }
    /**
     * <code>repeated .BuildingVO buildings = 1;</code>
     */
    public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder getBuildingsOrBuilder(
        int index) {
      return buildings_.get(index);
    }

    // optional bytes pngData = 2;
    public static final int PNGDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pngData_;
    /**
     * <code>optional bytes pngData = 2;</code>
     */
    public boolean hasPngData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes pngData = 2;</code>
     */
    public com.google.protobuf.ByteString getPngData() {
      return pngData_;
    }

    private void initFields() {
      buildings_ = java.util.Collections.emptyList();
      pngData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getBuildingsCount(); i++) {
        if (!getBuildings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < buildings_.size(); i++) {
        output.writeMessage(1, buildings_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, pngData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < buildings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buildings_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pngData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GMSaveFormation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.GMSaveFormationProtocal.internal_static_GMSaveFormation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.GMSaveFormationProtocal.internal_static_GMSaveFormation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.class, com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.Builder.class);
      }

      // Construct using com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuildingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (buildingsBuilder_ == null) {
          buildings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          buildingsBuilder_.clear();
        }
        pngData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.GMSaveFormationProtocal.internal_static_GMSaveFormation_descriptor;
      }

      public com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation getDefaultInstanceForType() {
        return com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.getDefaultInstance();
      }

      public com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation build() {
        com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation buildPartial() {
        com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation result = new com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (buildingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            buildings_ = java.util.Collections.unmodifiableList(buildings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.buildings_ = buildings_;
        } else {
          result.buildings_ = buildingsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pngData_ = pngData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation) {
          return mergeFrom((com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation other) {
        if (other == com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation.getDefaultInstance()) return this;
        if (buildingsBuilder_ == null) {
          if (!other.buildings_.isEmpty()) {
            if (buildings_.isEmpty()) {
              buildings_ = other.buildings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBuildingsIsMutable();
              buildings_.addAll(other.buildings_);
            }
            onChanged();
          }
        } else {
          if (!other.buildings_.isEmpty()) {
            if (buildingsBuilder_.isEmpty()) {
              buildingsBuilder_.dispose();
              buildingsBuilder_ = null;
              buildings_ = other.buildings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              buildingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBuildingsFieldBuilder() : null;
            } else {
              buildingsBuilder_.addAllMessages(other.buildings_);
            }
          }
        }
        if (other.hasPngData()) {
          setPngData(other.getPngData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getBuildingsCount(); i++) {
          if (!getBuildings(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.GMSaveFormationProtocal.GMSaveFormation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .BuildingVO buildings = 1;
      private java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> buildings_ =
        java.util.Collections.emptyList();
      private void ensureBuildingsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          buildings_ = new java.util.ArrayList<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO>(buildings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder> buildingsBuilder_;

      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> getBuildingsList() {
        if (buildingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buildings_);
        } else {
          return buildingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public int getBuildingsCount() {
        if (buildingsBuilder_ == null) {
          return buildings_.size();
        } else {
          return buildingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO getBuildings(int index) {
        if (buildingsBuilder_ == null) {
          return buildings_.get(index);
        } else {
          return buildingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder setBuildings(
          int index, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.set(index, value);
          onChanged();
        } else {
          buildingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder setBuildings(
          int index, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.set(index, builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder addBuildings(com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.add(value);
          onChanged();
        } else {
          buildingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder addBuildings(
          int index, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.add(index, value);
          onChanged();
        } else {
          buildingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder addBuildings(
          com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.add(builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder addBuildings(
          int index, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.add(index, builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder addAllBuildings(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO> values) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          super.addAll(values, buildings_);
          onChanged();
        } else {
          buildingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder clearBuildings() {
        if (buildingsBuilder_ == null) {
          buildings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          buildingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public Builder removeBuildings(int index) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.remove(index);
          onChanged();
        } else {
          buildingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder getBuildingsBuilder(
          int index) {
        return getBuildingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder getBuildingsOrBuilder(
          int index) {
        if (buildingsBuilder_ == null) {
          return buildings_.get(index);  } else {
          return buildingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder> 
           getBuildingsOrBuilderList() {
        if (buildingsBuilder_ != null) {
          return buildingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buildings_);
        }
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder addBuildingsBuilder() {
        return getBuildingsFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.getDefaultInstance());
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder addBuildingsBuilder(
          int index) {
        return getBuildingsFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.getDefaultInstance());
      }
      /**
       * <code>repeated .BuildingVO buildings = 1;</code>
       */
      public java.util.List<com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder> 
           getBuildingsBuilderList() {
        return getBuildingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder> 
          getBuildingsFieldBuilder() {
        if (buildingsBuilder_ == null) {
          buildingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVO.Builder, com.pureland.common.protocal.vo.BuildingVOProtocal.BuildingVOOrBuilder>(
                  buildings_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          buildings_ = null;
        }
        return buildingsBuilder_;
      }

      // optional bytes pngData = 2;
      private com.google.protobuf.ByteString pngData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pngData = 2;</code>
       */
      public boolean hasPngData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes pngData = 2;</code>
       */
      public com.google.protobuf.ByteString getPngData() {
        return pngData_;
      }
      /**
       * <code>optional bytes pngData = 2;</code>
       */
      public Builder setPngData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pngData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pngData = 2;</code>
       */
      public Builder clearPngData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pngData_ = getDefaultInstance().getPngData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GMSaveFormation)
    }

    static {
      defaultInstance = new GMSaveFormation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GMSaveFormation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GMSaveFormation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GMSaveFormation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GMSaveFormation.proto\032\020BuildingVO.prot" +
      "o\"B\n\017GMSaveFormation\022\036\n\tbuildings\030\001 \003(\0132" +
      "\013.BuildingVO\022\017\n\007pngData\030\002 \001(\014B7\n\034com.pur" +
      "eland.common.protocalB\027GMSaveFormationPr" +
      "otocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GMSaveFormation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GMSaveFormation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GMSaveFormation_descriptor,
              new java.lang.String[] { "Buildings", "PngData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.BuildingVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
