// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanBattleVO.proto

package com.pureland.common.protocal.vo;

public final class ClanBattleVOProtocal {
  private ClanBattleVOProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanBattleVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 clanBattleId = 1;
    /**
     * <code>optional int64 clanBattleId = 1;</code>
     *
     * <pre>
     *公会战id
     * </pre>
     */
    boolean hasClanBattleId();
    /**
     * <code>optional int64 clanBattleId = 1;</code>
     *
     * <pre>
     *公会战id
     * </pre>
     */
    long getClanBattleId();

    // optional .ClanBattleCampVO attackCampVO = 2;
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasAttackCampVO();
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getAttackCampVO();
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getAttackCampVOOrBuilder();

    // optional .ClanBattleCampVO defenceCampVO = 3;
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasDefenceCampVO();
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getDefenceCampVO();
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getDefenceCampVOOrBuilder();

    // optional int64 endTime = 4;
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    long getEndTime();

    // required int32 status = 5;
    /**
     * <code>required int32 status = 5;</code>
     *
     * <pre>
     *状态(0,1准备日,2战斗日3战斗日时间结束)
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 5;</code>
     *
     * <pre>
     *状态(0,1准备日,2战斗日3战斗日时间结束)
     * </pre>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code ClanBattleVO}
   */
  public static final class ClanBattleVO extends
      com.google.protobuf.GeneratedMessage
      implements ClanBattleVOOrBuilder {
    // Use ClanBattleVO.newBuilder() to construct.
    private ClanBattleVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanBattleVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanBattleVO defaultInstance;
    public static ClanBattleVO getDefaultInstance() {
      return defaultInstance;
    }

    public ClanBattleVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanBattleVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clanBattleId_ = input.readInt64();
              break;
            }
            case 18: {
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = attackCampVO_.toBuilder();
              }
              attackCampVO_ = input.readMessage(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attackCampVO_);
                attackCampVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = defenceCampVO_.toBuilder();
              }
              defenceCampVO_ = input.readMessage(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(defenceCampVO_);
                defenceCampVO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              endTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.ClanBattleVOProtocal.internal_static_ClanBattleVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.ClanBattleVOProtocal.internal_static_ClanBattleVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.class, com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanBattleVO> PARSER =
        new com.google.protobuf.AbstractParser<ClanBattleVO>() {
      public ClanBattleVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanBattleVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanBattleVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 clanBattleId = 1;
    public static final int CLANBATTLEID_FIELD_NUMBER = 1;
    private long clanBattleId_;
    /**
     * <code>optional int64 clanBattleId = 1;</code>
     *
     * <pre>
     *公会战id
     * </pre>
     */
    public boolean hasClanBattleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 clanBattleId = 1;</code>
     *
     * <pre>
     *公会战id
     * </pre>
     */
    public long getClanBattleId() {
      return clanBattleId_;
    }

    // optional .ClanBattleCampVO attackCampVO = 2;
    public static final int ATTACKCAMPVO_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO attackCampVO_;
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasAttackCampVO() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getAttackCampVO() {
      return attackCampVO_;
    }
    /**
     * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getAttackCampVOOrBuilder() {
      return attackCampVO_;
    }

    // optional .ClanBattleCampVO defenceCampVO = 3;
    public static final int DEFENCECAMPVO_FIELD_NUMBER = 3;
    private com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO defenceCampVO_;
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasDefenceCampVO() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getDefenceCampVO() {
      return defenceCampVO_;
    }
    /**
     * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getDefenceCampVOOrBuilder() {
      return defenceCampVO_;
    }

    // optional int64 endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private long endTime_;
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    // required int32 status = 5;
    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>required int32 status = 5;</code>
     *
     * <pre>
     *状态(0,1准备日,2战斗日3战斗日时间结束)
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 status = 5;</code>
     *
     * <pre>
     *状态(0,1准备日,2战斗日3战斗日时间结束)
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      clanBattleId_ = 0L;
      attackCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
      defenceCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
      endTime_ = 0L;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAttackCampVO()) {
        if (!getAttackCampVO().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDefenceCampVO()) {
        if (!getDefenceCampVO().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clanBattleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, attackCampVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, defenceCampVO_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, endTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clanBattleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attackCampVO_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, defenceCampVO_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanBattleVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.ClanBattleVOProtocal.internal_static_ClanBattleVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.ClanBattleVOProtocal.internal_static_ClanBattleVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.class, com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttackCampVOFieldBuilder();
          getDefenceCampVOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clanBattleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attackCampVOBuilder_ == null) {
          attackCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
        } else {
          attackCampVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (defenceCampVOBuilder_ == null) {
          defenceCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
        } else {
          defenceCampVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.ClanBattleVOProtocal.internal_static_ClanBattleVO_descriptor;
      }

      public com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO build() {
        com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO buildPartial() {
        com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO result = new com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clanBattleId_ = clanBattleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (attackCampVOBuilder_ == null) {
          result.attackCampVO_ = attackCampVO_;
        } else {
          result.attackCampVO_ = attackCampVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (defenceCampVOBuilder_ == null) {
          result.defenceCampVO_ = defenceCampVO_;
        } else {
          result.defenceCampVO_ = defenceCampVOBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO) {
          return mergeFrom((com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO other) {
        if (other == com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO.getDefaultInstance()) return this;
        if (other.hasClanBattleId()) {
          setClanBattleId(other.getClanBattleId());
        }
        if (other.hasAttackCampVO()) {
          mergeAttackCampVO(other.getAttackCampVO());
        }
        if (other.hasDefenceCampVO()) {
          mergeDefenceCampVO(other.getDefenceCampVO());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        if (hasAttackCampVO()) {
          if (!getAttackCampVO().isInitialized()) {
            
            return false;
          }
        }
        if (hasDefenceCampVO()) {
          if (!getDefenceCampVO().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.ClanBattleVOProtocal.ClanBattleVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 clanBattleId = 1;
      private long clanBattleId_ ;
      /**
       * <code>optional int64 clanBattleId = 1;</code>
       *
       * <pre>
       *公会战id
       * </pre>
       */
      public boolean hasClanBattleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 clanBattleId = 1;</code>
       *
       * <pre>
       *公会战id
       * </pre>
       */
      public long getClanBattleId() {
        return clanBattleId_;
      }
      /**
       * <code>optional int64 clanBattleId = 1;</code>
       *
       * <pre>
       *公会战id
       * </pre>
       */
      public Builder setClanBattleId(long value) {
        bitField0_ |= 0x00000001;
        clanBattleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clanBattleId = 1;</code>
       *
       * <pre>
       *公会战id
       * </pre>
       */
      public Builder clearClanBattleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clanBattleId_ = 0L;
        onChanged();
        return this;
      }

      // optional .ClanBattleCampVO attackCampVO = 2;
      private com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO attackCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder> attackCampVOBuilder_;
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasAttackCampVO() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getAttackCampVO() {
        if (attackCampVOBuilder_ == null) {
          return attackCampVO_;
        } else {
          return attackCampVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setAttackCampVO(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO value) {
        if (attackCampVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attackCampVO_ = value;
          onChanged();
        } else {
          attackCampVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setAttackCampVO(
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder builderForValue) {
        if (attackCampVOBuilder_ == null) {
          attackCampVO_ = builderForValue.build();
          onChanged();
        } else {
          attackCampVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder mergeAttackCampVO(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO value) {
        if (attackCampVOBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              attackCampVO_ != com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance()) {
            attackCampVO_ =
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.newBuilder(attackCampVO_).mergeFrom(value).buildPartial();
          } else {
            attackCampVO_ = value;
          }
          onChanged();
        } else {
          attackCampVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearAttackCampVO() {
        if (attackCampVOBuilder_ == null) {
          attackCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
          onChanged();
        } else {
          attackCampVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder getAttackCampVOBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAttackCampVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getAttackCampVOOrBuilder() {
        if (attackCampVOBuilder_ != null) {
          return attackCampVOBuilder_.getMessageOrBuilder();
        } else {
          return attackCampVO_;
        }
      }
      /**
       * <code>optional .ClanBattleCampVO attackCampVO = 2;</code>
       *
       * <pre>
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder> 
          getAttackCampVOFieldBuilder() {
        if (attackCampVOBuilder_ == null) {
          attackCampVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder>(
                  attackCampVO_,
                  getParentForChildren(),
                  isClean());
          attackCampVO_ = null;
        }
        return attackCampVOBuilder_;
      }

      // optional .ClanBattleCampVO defenceCampVO = 3;
      private com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO defenceCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder> defenceCampVOBuilder_;
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasDefenceCampVO() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getDefenceCampVO() {
        if (defenceCampVOBuilder_ == null) {
          return defenceCampVO_;
        } else {
          return defenceCampVOBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setDefenceCampVO(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO value) {
        if (defenceCampVOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          defenceCampVO_ = value;
          onChanged();
        } else {
          defenceCampVOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setDefenceCampVO(
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder builderForValue) {
        if (defenceCampVOBuilder_ == null) {
          defenceCampVO_ = builderForValue.build();
          onChanged();
        } else {
          defenceCampVOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder mergeDefenceCampVO(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO value) {
        if (defenceCampVOBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              defenceCampVO_ != com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance()) {
            defenceCampVO_ =
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.newBuilder(defenceCampVO_).mergeFrom(value).buildPartial();
          } else {
            defenceCampVO_ = value;
          }
          onChanged();
        } else {
          defenceCampVOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearDefenceCampVO() {
        if (defenceCampVOBuilder_ == null) {
          defenceCampVO_ = com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
          onChanged();
        } else {
          defenceCampVOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder getDefenceCampVOBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDefenceCampVOFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder getDefenceCampVOOrBuilder() {
        if (defenceCampVOBuilder_ != null) {
          return defenceCampVOBuilder_.getMessageOrBuilder();
        } else {
          return defenceCampVO_;
        }
      }
      /**
       * <code>optional .ClanBattleCampVO defenceCampVO = 3;</code>
       *
       * <pre>
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder> 
          getDefenceCampVOFieldBuilder() {
        if (defenceCampVOBuilder_ == null) {
          defenceCampVOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder>(
                  defenceCampVO_,
                  getParentForChildren(),
                  isClean());
          defenceCampVO_ = null;
        }
        return defenceCampVOBuilder_;
      }

      // optional int64 endTime = 4;
      private long endTime_ ;
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTime = 4;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // required int32 status = 5;
      private int status_ ;
      /**
       * <code>required int32 status = 5;</code>
       *
       * <pre>
       *状态(0,1准备日,2战斗日3战斗日时间结束)
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 status = 5;</code>
       *
       * <pre>
       *状态(0,1准备日,2战斗日3战斗日时间结束)
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 5;</code>
       *
       * <pre>
       *状态(0,1准备日,2战斗日3战斗日时间结束)
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000010;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 5;</code>
       *
       * <pre>
       *状态(0,1准备日,2战斗日3战斗日时间结束)
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClanBattleVO)
    }

    static {
      defaultInstance = new ClanBattleVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanBattleVO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanBattleVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanBattleVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ClanBattleVO.proto\032\026ClanBattleCampVO.p" +
      "roto\"\230\001\n\014ClanBattleVO\022\024\n\014clanBattleId\030\001 " +
      "\001(\003\022\'\n\014attackCampVO\030\002 \001(\0132\021.ClanBattleCa" +
      "mpVO\022(\n\rdefenceCampVO\030\003 \001(\0132\021.ClanBattle" +
      "CampVO\022\017\n\007endTime\030\004 \001(\003\022\016\n\006status\030\005 \002(\005B" +
      "7\n\037com.pureland.common.protocal.voB\024Clan" +
      "BattleVOProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanBattleVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanBattleVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanBattleVO_descriptor,
              new java.lang.String[] { "ClanBattleId", "AttackCampVO", "DefenceCampVO", "EndTime", "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
