// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanBattleCampVO.proto

package com.pureland.common.protocal.vo;

public final class ClanBattleCampVOProtocal {
  private ClanBattleCampVOProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanBattleCampVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 clanId = 1;
    /**
     * <code>optional int64 clanId = 1;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasClanId();
    /**
     * <code>optional int64 clanId = 1;</code>
     *
     * <pre>
     * </pre>
     */
    long getClanId();

    // optional string clanName = 2;
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasClanName();
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getClanName();
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getClanNameBytes();

    // optional string clanIcon = 3;
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasClanIcon();
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getClanIcon();
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getClanIconBytes();

    // optional int32 score = 4;
    /**
     * <code>optional int32 score = 4;</code>
     *
     * <pre>
     *	
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 4;</code>
     *
     * <pre>
     *	
     * </pre>
     */
    int getScore();

    // optional int32 attackCountNow = 5;
    /**
     * <code>optional int32 attackCountNow = 5;</code>
     *
     * <pre>
     *攻击次数
     * </pre>
     */
    boolean hasAttackCountNow();
    /**
     * <code>optional int32 attackCountNow = 5;</code>
     *
     * <pre>
     *攻击次数
     * </pre>
     */
    int getAttackCountNow();

    // repeated .ClanBattleMemberVO clanBattleMembers = 6;
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> 
        getClanBattleMembersList();
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO getClanBattleMembers(int index);
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    int getClanBattleMembersCount();
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<? extends com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder> 
        getClanBattleMembersOrBuilderList();
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder getClanBattleMembersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ClanBattleCampVO}
   */
  public static final class ClanBattleCampVO extends
      com.google.protobuf.GeneratedMessage
      implements ClanBattleCampVOOrBuilder {
    // Use ClanBattleCampVO.newBuilder() to construct.
    private ClanBattleCampVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanBattleCampVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanBattleCampVO defaultInstance;
    public static ClanBattleCampVO getDefaultInstance() {
      return defaultInstance;
    }

    public ClanBattleCampVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanBattleCampVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clanId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clanName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              clanIcon_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              score_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              attackCountNow_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                clanBattleMembers_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO>();
                mutable_bitField0_ |= 0x00000020;
              }
              clanBattleMembers_.add(input.readMessage(com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          clanBattleMembers_ = java.util.Collections.unmodifiableList(clanBattleMembers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.internal_static_ClanBattleCampVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.internal_static_ClanBattleCampVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.class, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanBattleCampVO> PARSER =
        new com.google.protobuf.AbstractParser<ClanBattleCampVO>() {
      public ClanBattleCampVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanBattleCampVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanBattleCampVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 clanId = 1;
    public static final int CLANID_FIELD_NUMBER = 1;
    private long clanId_;
    /**
     * <code>optional int64 clanId = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasClanId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 clanId = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public long getClanId() {
      return clanId_;
    }

    // optional string clanName = 2;
    public static final int CLANNAME_FIELD_NUMBER = 2;
    private java.lang.Object clanName_;
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasClanName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getClanName() {
      java.lang.Object ref = clanName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clanName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clanName = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClanNameBytes() {
      java.lang.Object ref = clanName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clanName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string clanIcon = 3;
    public static final int CLANICON_FIELD_NUMBER = 3;
    private java.lang.Object clanIcon_;
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasClanIcon() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getClanIcon() {
      java.lang.Object ref = clanIcon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clanIcon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clanIcon = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClanIconBytes() {
      java.lang.Object ref = clanIcon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clanIcon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 score = 4;
    public static final int SCORE_FIELD_NUMBER = 4;
    private int score_;
    /**
     * <code>optional int32 score = 4;</code>
     *
     * <pre>
     *	
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 score = 4;</code>
     *
     * <pre>
     *	
     * </pre>
     */
    public int getScore() {
      return score_;
    }

    // optional int32 attackCountNow = 5;
    public static final int ATTACKCOUNTNOW_FIELD_NUMBER = 5;
    private int attackCountNow_;
    /**
     * <code>optional int32 attackCountNow = 5;</code>
     *
     * <pre>
     *攻击次数
     * </pre>
     */
    public boolean hasAttackCountNow() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 attackCountNow = 5;</code>
     *
     * <pre>
     *攻击次数
     * </pre>
     */
    public int getAttackCountNow() {
      return attackCountNow_;
    }

    // repeated .ClanBattleMemberVO clanBattleMembers = 6;
    public static final int CLANBATTLEMEMBERS_FIELD_NUMBER = 6;
    private java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> clanBattleMembers_;
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> getClanBattleMembersList() {
      return clanBattleMembers_;
    }
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<? extends com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder> 
        getClanBattleMembersOrBuilderList() {
      return clanBattleMembers_;
    }
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public int getClanBattleMembersCount() {
      return clanBattleMembers_.size();
    }
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO getClanBattleMembers(int index) {
      return clanBattleMembers_.get(index);
    }
    /**
     * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder getClanBattleMembersOrBuilder(
        int index) {
      return clanBattleMembers_.get(index);
    }

    private void initFields() {
      clanId_ = 0L;
      clanName_ = "";
      clanIcon_ = "";
      score_ = 0;
      attackCountNow_ = 0;
      clanBattleMembers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getClanBattleMembersCount(); i++) {
        if (!getClanBattleMembers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clanId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClanNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClanIconBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, score_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, attackCountNow_);
      }
      for (int i = 0; i < clanBattleMembers_.size(); i++) {
        output.writeMessage(6, clanBattleMembers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clanId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClanNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClanIconBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, score_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, attackCountNow_);
      }
      for (int i = 0; i < clanBattleMembers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, clanBattleMembers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanBattleCampVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.internal_static_ClanBattleCampVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.internal_static_ClanBattleCampVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.class, com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClanBattleMembersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clanName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        clanIcon_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        attackCountNow_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (clanBattleMembersBuilder_ == null) {
          clanBattleMembers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          clanBattleMembersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.internal_static_ClanBattleCampVO_descriptor;
      }

      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO build() {
        com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO buildPartial() {
        com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO result = new com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clanId_ = clanId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clanName_ = clanName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clanIcon_ = clanIcon_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.attackCountNow_ = attackCountNow_;
        if (clanBattleMembersBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            clanBattleMembers_ = java.util.Collections.unmodifiableList(clanBattleMembers_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.clanBattleMembers_ = clanBattleMembers_;
        } else {
          result.clanBattleMembers_ = clanBattleMembersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO) {
          return mergeFrom((com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO other) {
        if (other == com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO.getDefaultInstance()) return this;
        if (other.hasClanId()) {
          setClanId(other.getClanId());
        }
        if (other.hasClanName()) {
          bitField0_ |= 0x00000002;
          clanName_ = other.clanName_;
          onChanged();
        }
        if (other.hasClanIcon()) {
          bitField0_ |= 0x00000004;
          clanIcon_ = other.clanIcon_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasAttackCountNow()) {
          setAttackCountNow(other.getAttackCountNow());
        }
        if (clanBattleMembersBuilder_ == null) {
          if (!other.clanBattleMembers_.isEmpty()) {
            if (clanBattleMembers_.isEmpty()) {
              clanBattleMembers_ = other.clanBattleMembers_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureClanBattleMembersIsMutable();
              clanBattleMembers_.addAll(other.clanBattleMembers_);
            }
            onChanged();
          }
        } else {
          if (!other.clanBattleMembers_.isEmpty()) {
            if (clanBattleMembersBuilder_.isEmpty()) {
              clanBattleMembersBuilder_.dispose();
              clanBattleMembersBuilder_ = null;
              clanBattleMembers_ = other.clanBattleMembers_;
              bitField0_ = (bitField0_ & ~0x00000020);
              clanBattleMembersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getClanBattleMembersFieldBuilder() : null;
            } else {
              clanBattleMembersBuilder_.addAllMessages(other.clanBattleMembers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getClanBattleMembersCount(); i++) {
          if (!getClanBattleMembers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.ClanBattleCampVOProtocal.ClanBattleCampVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 clanId = 1;
      private long clanId_ ;
      /**
       * <code>optional int64 clanId = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasClanId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 clanId = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public long getClanId() {
        return clanId_;
      }
      /**
       * <code>optional int64 clanId = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanId(long value) {
        bitField0_ |= 0x00000001;
        clanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clanId = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearClanId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clanId_ = 0L;
        onChanged();
        return this;
      }

      // optional string clanName = 2;
      private java.lang.Object clanName_ = "";
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasClanName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getClanName() {
        java.lang.Object ref = clanName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clanName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClanNameBytes() {
        java.lang.Object ref = clanName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clanName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clanName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearClanName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clanName_ = getDefaultInstance().getClanName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanName = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clanName_ = value;
        onChanged();
        return this;
      }

      // optional string clanIcon = 3;
      private java.lang.Object clanIcon_ = "";
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasClanIcon() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getClanIcon() {
        java.lang.Object ref = clanIcon_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clanIcon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClanIconBytes() {
        java.lang.Object ref = clanIcon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clanIcon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clanIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearClanIcon() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clanIcon_ = getDefaultInstance().getClanIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanIcon = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clanIcon_ = value;
        onChanged();
        return this;
      }

      // optional int32 score = 4;
      private int score_ ;
      /**
       * <code>optional int32 score = 4;</code>
       *
       * <pre>
       *	
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 score = 4;</code>
       *
       * <pre>
       *	
       * </pre>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 4;</code>
       *
       * <pre>
       *	
       * </pre>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000008;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 4;</code>
       *
       * <pre>
       *	
       * </pre>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = 0;
        onChanged();
        return this;
      }

      // optional int32 attackCountNow = 5;
      private int attackCountNow_ ;
      /**
       * <code>optional int32 attackCountNow = 5;</code>
       *
       * <pre>
       *攻击次数
       * </pre>
       */
      public boolean hasAttackCountNow() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 attackCountNow = 5;</code>
       *
       * <pre>
       *攻击次数
       * </pre>
       */
      public int getAttackCountNow() {
        return attackCountNow_;
      }
      /**
       * <code>optional int32 attackCountNow = 5;</code>
       *
       * <pre>
       *攻击次数
       * </pre>
       */
      public Builder setAttackCountNow(int value) {
        bitField0_ |= 0x00000010;
        attackCountNow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 attackCountNow = 5;</code>
       *
       * <pre>
       *攻击次数
       * </pre>
       */
      public Builder clearAttackCountNow() {
        bitField0_ = (bitField0_ & ~0x00000010);
        attackCountNow_ = 0;
        onChanged();
        return this;
      }

      // repeated .ClanBattleMemberVO clanBattleMembers = 6;
      private java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> clanBattleMembers_ =
        java.util.Collections.emptyList();
      private void ensureClanBattleMembersIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          clanBattleMembers_ = new java.util.ArrayList<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO>(clanBattleMembers_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder> clanBattleMembersBuilder_;

      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> getClanBattleMembersList() {
        if (clanBattleMembersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clanBattleMembers_);
        } else {
          return clanBattleMembersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public int getClanBattleMembersCount() {
        if (clanBattleMembersBuilder_ == null) {
          return clanBattleMembers_.size();
        } else {
          return clanBattleMembersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO getClanBattleMembers(int index) {
        if (clanBattleMembersBuilder_ == null) {
          return clanBattleMembers_.get(index);
        } else {
          return clanBattleMembersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanBattleMembers(
          int index, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO value) {
        if (clanBattleMembersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.set(index, value);
          onChanged();
        } else {
          clanBattleMembersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanBattleMembers(
          int index, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder builderForValue) {
        if (clanBattleMembersBuilder_ == null) {
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.set(index, builderForValue.build());
          onChanged();
        } else {
          clanBattleMembersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addClanBattleMembers(com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO value) {
        if (clanBattleMembersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.add(value);
          onChanged();
        } else {
          clanBattleMembersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addClanBattleMembers(
          int index, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO value) {
        if (clanBattleMembersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.add(index, value);
          onChanged();
        } else {
          clanBattleMembersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addClanBattleMembers(
          com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder builderForValue) {
        if (clanBattleMembersBuilder_ == null) {
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.add(builderForValue.build());
          onChanged();
        } else {
          clanBattleMembersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addClanBattleMembers(
          int index, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder builderForValue) {
        if (clanBattleMembersBuilder_ == null) {
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.add(index, builderForValue.build());
          onChanged();
        } else {
          clanBattleMembersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addAllClanBattleMembers(
          java.lang.Iterable<? extends com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO> values) {
        if (clanBattleMembersBuilder_ == null) {
          ensureClanBattleMembersIsMutable();
          super.addAll(values, clanBattleMembers_);
          onChanged();
        } else {
          clanBattleMembersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearClanBattleMembers() {
        if (clanBattleMembersBuilder_ == null) {
          clanBattleMembers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          clanBattleMembersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder removeClanBattleMembers(int index) {
        if (clanBattleMembersBuilder_ == null) {
          ensureClanBattleMembersIsMutable();
          clanBattleMembers_.remove(index);
          onChanged();
        } else {
          clanBattleMembersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder getClanBattleMembersBuilder(
          int index) {
        return getClanBattleMembersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder getClanBattleMembersOrBuilder(
          int index) {
        if (clanBattleMembersBuilder_ == null) {
          return clanBattleMembers_.get(index);  } else {
          return clanBattleMembersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<? extends com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder> 
           getClanBattleMembersOrBuilderList() {
        if (clanBattleMembersBuilder_ != null) {
          return clanBattleMembersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clanBattleMembers_);
        }
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder addClanBattleMembersBuilder() {
        return getClanBattleMembersFieldBuilder().addBuilder(
            com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder addClanBattleMembersBuilder(
          int index) {
        return getClanBattleMembersFieldBuilder().addBuilder(
            index, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.getDefaultInstance());
      }
      /**
       * <code>repeated .ClanBattleMemberVO clanBattleMembers = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder> 
           getClanBattleMembersBuilderList() {
        return getClanBattleMembersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder> 
          getClanBattleMembersFieldBuilder() {
        if (clanBattleMembersBuilder_ == null) {
          clanBattleMembersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVO.Builder, com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.ClanBattleMemberVOOrBuilder>(
                  clanBattleMembers_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          clanBattleMembers_ = null;
        }
        return clanBattleMembersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClanBattleCampVO)
    }

    static {
      defaultInstance = new ClanBattleCampVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanBattleCampVO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanBattleCampVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanBattleCampVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ClanBattleCampVO.proto\032\030ClanBattleMemb" +
      "erVO.proto\"\235\001\n\020ClanBattleCampVO\022\016\n\006clanI" +
      "d\030\001 \001(\003\022\020\n\010clanName\030\002 \001(\t\022\020\n\010clanIcon\030\003 " +
      "\001(\t\022\r\n\005score\030\004 \001(\005\022\026\n\016attackCountNow\030\005 \001" +
      "(\005\022.\n\021clanBattleMembers\030\006 \003(\0132\023.ClanBatt" +
      "leMemberVOB;\n\037com.pureland.common.protoc" +
      "al.voB\030ClanBattleCampVOProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanBattleCampVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanBattleCampVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanBattleCampVO_descriptor,
              new java.lang.String[] { "ClanId", "ClanName", "ClanIcon", "Score", "AttackCountNow", "ClanBattleMembers", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.pureland.common.protocal.vo.ClanBattleMemberVOProtocal.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
