// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClanBattleStatisticsVO.proto

package com.pureland.common.protocal.vo;

public final class ClanBattleStatisticsVOProtocal {
  private ClanBattleStatisticsVOProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClanBattleStatisticsVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .ClanBattleStatisticsBeanVO attack = 1;
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    boolean hasAttack();
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getAttack();
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getAttackOrBuilder();

    // optional .ClanBattleStatisticsBeanVO defence = 2;
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    boolean hasDefence();
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getDefence();
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getDefenceOrBuilder();
  }
  /**
   * Protobuf type {@code ClanBattleStatisticsVO}
   */
  public static final class ClanBattleStatisticsVO extends
      com.google.protobuf.GeneratedMessage
      implements ClanBattleStatisticsVOOrBuilder {
    // Use ClanBattleStatisticsVO.newBuilder() to construct.
    private ClanBattleStatisticsVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanBattleStatisticsVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanBattleStatisticsVO defaultInstance;
    public static ClanBattleStatisticsVO getDefaultInstance() {
      return defaultInstance;
    }

    public ClanBattleStatisticsVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanBattleStatisticsVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = attack_.toBuilder();
              }
              attack_ = input.readMessage(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attack_);
                attack_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = defence_.toBuilder();
              }
              defence_ = input.readMessage(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(defence_);
                defence_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.class, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanBattleStatisticsVO> PARSER =
        new com.google.protobuf.AbstractParser<ClanBattleStatisticsVO>() {
      public ClanBattleStatisticsVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanBattleStatisticsVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanBattleStatisticsVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .ClanBattleStatisticsBeanVO attack = 1;
    public static final int ATTACK_FIELD_NUMBER = 1;
    private com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO attack_;
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    public boolean hasAttack() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getAttack() {
      return attack_;
    }
    /**
     * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
     */
    public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getAttackOrBuilder() {
      return attack_;
    }

    // optional .ClanBattleStatisticsBeanVO defence = 2;
    public static final int DEFENCE_FIELD_NUMBER = 2;
    private com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO defence_;
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    public boolean hasDefence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getDefence() {
      return defence_;
    }
    /**
     * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
     */
    public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getDefenceOrBuilder() {
      return defence_;
    }

    private void initFields() {
      attack_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
      defence_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, attack_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, defence_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attack_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, defence_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanBattleStatisticsVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.class, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttackFieldBuilder();
          getDefenceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (attackBuilder_ == null) {
          attack_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
        } else {
          attackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (defenceBuilder_ == null) {
          defence_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
        } else {
          defenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsVO_descriptor;
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO build() {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO buildPartial() {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO result = new com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (attackBuilder_ == null) {
          result.attack_ = attack_;
        } else {
          result.attack_ = attackBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (defenceBuilder_ == null) {
          result.defence_ = defence_;
        } else {
          result.defence_ = defenceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO) {
          return mergeFrom((com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO other) {
        if (other == com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO.getDefaultInstance()) return this;
        if (other.hasAttack()) {
          mergeAttack(other.getAttack());
        }
        if (other.hasDefence()) {
          mergeDefence(other.getDefence());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .ClanBattleStatisticsBeanVO attack = 1;
      private com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO attack_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder> attackBuilder_;
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public boolean hasAttack() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getAttack() {
        if (attackBuilder_ == null) {
          return attack_;
        } else {
          return attackBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public Builder setAttack(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO value) {
        if (attackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          attack_ = value;
          onChanged();
        } else {
          attackBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public Builder setAttack(
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder builderForValue) {
        if (attackBuilder_ == null) {
          attack_ = builderForValue.build();
          onChanged();
        } else {
          attackBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public Builder mergeAttack(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO value) {
        if (attackBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              attack_ != com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance()) {
            attack_ =
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.newBuilder(attack_).mergeFrom(value).buildPartial();
          } else {
            attack_ = value;
          }
          onChanged();
        } else {
          attackBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public Builder clearAttack() {
        if (attackBuilder_ == null) {
          attack_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
          onChanged();
        } else {
          attackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder getAttackBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAttackFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getAttackOrBuilder() {
        if (attackBuilder_ != null) {
          return attackBuilder_.getMessageOrBuilder();
        } else {
          return attack_;
        }
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO attack = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder> 
          getAttackFieldBuilder() {
        if (attackBuilder_ == null) {
          attackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder>(
                  attack_,
                  getParentForChildren(),
                  isClean());
          attack_ = null;
        }
        return attackBuilder_;
      }

      // optional .ClanBattleStatisticsBeanVO defence = 2;
      private com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO defence_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder> defenceBuilder_;
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public boolean hasDefence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getDefence() {
        if (defenceBuilder_ == null) {
          return defence_;
        } else {
          return defenceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public Builder setDefence(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO value) {
        if (defenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          defence_ = value;
          onChanged();
        } else {
          defenceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public Builder setDefence(
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder builderForValue) {
        if (defenceBuilder_ == null) {
          defence_ = builderForValue.build();
          onChanged();
        } else {
          defenceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public Builder mergeDefence(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO value) {
        if (defenceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              defence_ != com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance()) {
            defence_ =
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.newBuilder(defence_).mergeFrom(value).buildPartial();
          } else {
            defence_ = value;
          }
          onChanged();
        } else {
          defenceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public Builder clearDefence() {
        if (defenceBuilder_ == null) {
          defence_ = com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
          onChanged();
        } else {
          defenceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder getDefenceBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDefenceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder getDefenceOrBuilder() {
        if (defenceBuilder_ != null) {
          return defenceBuilder_.getMessageOrBuilder();
        } else {
          return defence_;
        }
      }
      /**
       * <code>optional .ClanBattleStatisticsBeanVO defence = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder> 
          getDefenceFieldBuilder() {
        if (defenceBuilder_ == null) {
          defenceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder>(
                  defence_,
                  getParentForChildren(),
                  isClean());
          defence_ = null;
        }
        return defenceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ClanBattleStatisticsVO)
    }

    static {
      defaultInstance = new ClanBattleStatisticsVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanBattleStatisticsVO)
  }

  public interface ClanBattleStatisticsBeanVOOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string clanName = 1;
    /**
     * <code>optional string clanName = 1;</code>
     */
    boolean hasClanName();
    /**
     * <code>optional string clanName = 1;</code>
     */
    java.lang.String getClanName();
    /**
     * <code>optional string clanName = 1;</code>
     */
    com.google.protobuf.ByteString
        getClanNameBytes();

    // optional string clanIcon = 2;
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasClanIcon();
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getClanIcon();
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getClanIconBytes();

    // optional int32 score = 3;
    /**
     * <code>optional int32 score = 3;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>optional int32 score = 3;</code>
     *
     * <pre>
     * </pre>
     */
    int getScore();

    // optional int32 totalAttackCount = 4;
    /**
     * <code>optional int32 totalAttackCount = 4;</code>
     */
    boolean hasTotalAttackCount();
    /**
     * <code>optional int32 totalAttackCount = 4;</code>
     */
    int getTotalAttackCount();

    // optional int32 winAttackCount = 5;
    /**
     * <code>optional int32 winAttackCount = 5;</code>
     */
    boolean hasWinAttackCount();
    /**
     * <code>optional int32 winAttackCount = 5;</code>
     */
    int getWinAttackCount();

    // optional int32 loseAttackCount = 6;
    /**
     * <code>optional int32 loseAttackCount = 6;</code>
     */
    boolean hasLoseAttackCount();
    /**
     * <code>optional int32 loseAttackCount = 6;</code>
     */
    int getLoseAttackCount();

    // optional int32 leftAttackCount = 7;
    /**
     * <code>optional int32 leftAttackCount = 7;</code>
     */
    boolean hasLeftAttackCount();
    /**
     * <code>optional int32 leftAttackCount = 7;</code>
     */
    int getLeftAttackCount();

    // optional int32 threeStarWin = 8;
    /**
     * <code>optional int32 threeStarWin = 8;</code>
     */
    boolean hasThreeStarWin();
    /**
     * <code>optional int32 threeStarWin = 8;</code>
     */
    int getThreeStarWin();

    // optional int32 twoStarWin = 9;
    /**
     * <code>optional int32 twoStarWin = 9;</code>
     */
    boolean hasTwoStarWin();
    /**
     * <code>optional int32 twoStarWin = 9;</code>
     */
    int getTwoStarWin();

    // optional int32 oneStarWin = 10;
    /**
     * <code>optional int32 oneStarWin = 10;</code>
     */
    boolean hasOneStarWin();
    /**
     * <code>optional int32 oneStarWin = 10;</code>
     */
    int getOneStarWin();
  }
  /**
   * Protobuf type {@code ClanBattleStatisticsBeanVO}
   */
  public static final class ClanBattleStatisticsBeanVO extends
      com.google.protobuf.GeneratedMessage
      implements ClanBattleStatisticsBeanVOOrBuilder {
    // Use ClanBattleStatisticsBeanVO.newBuilder() to construct.
    private ClanBattleStatisticsBeanVO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClanBattleStatisticsBeanVO(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClanBattleStatisticsBeanVO defaultInstance;
    public static ClanBattleStatisticsBeanVO getDefaultInstance() {
      return defaultInstance;
    }

    public ClanBattleStatisticsBeanVO getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClanBattleStatisticsBeanVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clanName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clanIcon_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              score_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              totalAttackCount_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              winAttackCount_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              loseAttackCount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              leftAttackCount_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              threeStarWin_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              twoStarWin_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              oneStarWin_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsBeanVO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsBeanVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.class, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder.class);
    }

    public static com.google.protobuf.Parser<ClanBattleStatisticsBeanVO> PARSER =
        new com.google.protobuf.AbstractParser<ClanBattleStatisticsBeanVO>() {
      public ClanBattleStatisticsBeanVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClanBattleStatisticsBeanVO(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClanBattleStatisticsBeanVO> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string clanName = 1;
    public static final int CLANNAME_FIELD_NUMBER = 1;
    private java.lang.Object clanName_;
    /**
     * <code>optional string clanName = 1;</code>
     */
    public boolean hasClanName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string clanName = 1;</code>
     */
    public java.lang.String getClanName() {
      java.lang.Object ref = clanName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clanName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clanName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClanNameBytes() {
      java.lang.Object ref = clanName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clanName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string clanIcon = 2;
    public static final int CLANICON_FIELD_NUMBER = 2;
    private java.lang.Object clanIcon_;
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasClanIcon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getClanIcon() {
      java.lang.Object ref = clanIcon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clanIcon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clanIcon = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClanIconBytes() {
      java.lang.Object ref = clanIcon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clanIcon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 score = 3;
    public static final int SCORE_FIELD_NUMBER = 3;
    private int score_;
    /**
     * <code>optional int32 score = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 score = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public int getScore() {
      return score_;
    }

    // optional int32 totalAttackCount = 4;
    public static final int TOTALATTACKCOUNT_FIELD_NUMBER = 4;
    private int totalAttackCount_;
    /**
     * <code>optional int32 totalAttackCount = 4;</code>
     */
    public boolean hasTotalAttackCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 totalAttackCount = 4;</code>
     */
    public int getTotalAttackCount() {
      return totalAttackCount_;
    }

    // optional int32 winAttackCount = 5;
    public static final int WINATTACKCOUNT_FIELD_NUMBER = 5;
    private int winAttackCount_;
    /**
     * <code>optional int32 winAttackCount = 5;</code>
     */
    public boolean hasWinAttackCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 winAttackCount = 5;</code>
     */
    public int getWinAttackCount() {
      return winAttackCount_;
    }

    // optional int32 loseAttackCount = 6;
    public static final int LOSEATTACKCOUNT_FIELD_NUMBER = 6;
    private int loseAttackCount_;
    /**
     * <code>optional int32 loseAttackCount = 6;</code>
     */
    public boolean hasLoseAttackCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 loseAttackCount = 6;</code>
     */
    public int getLoseAttackCount() {
      return loseAttackCount_;
    }

    // optional int32 leftAttackCount = 7;
    public static final int LEFTATTACKCOUNT_FIELD_NUMBER = 7;
    private int leftAttackCount_;
    /**
     * <code>optional int32 leftAttackCount = 7;</code>
     */
    public boolean hasLeftAttackCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 leftAttackCount = 7;</code>
     */
    public int getLeftAttackCount() {
      return leftAttackCount_;
    }

    // optional int32 threeStarWin = 8;
    public static final int THREESTARWIN_FIELD_NUMBER = 8;
    private int threeStarWin_;
    /**
     * <code>optional int32 threeStarWin = 8;</code>
     */
    public boolean hasThreeStarWin() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 threeStarWin = 8;</code>
     */
    public int getThreeStarWin() {
      return threeStarWin_;
    }

    // optional int32 twoStarWin = 9;
    public static final int TWOSTARWIN_FIELD_NUMBER = 9;
    private int twoStarWin_;
    /**
     * <code>optional int32 twoStarWin = 9;</code>
     */
    public boolean hasTwoStarWin() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 twoStarWin = 9;</code>
     */
    public int getTwoStarWin() {
      return twoStarWin_;
    }

    // optional int32 oneStarWin = 10;
    public static final int ONESTARWIN_FIELD_NUMBER = 10;
    private int oneStarWin_;
    /**
     * <code>optional int32 oneStarWin = 10;</code>
     */
    public boolean hasOneStarWin() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 oneStarWin = 10;</code>
     */
    public int getOneStarWin() {
      return oneStarWin_;
    }

    private void initFields() {
      clanName_ = "";
      clanIcon_ = "";
      score_ = 0;
      totalAttackCount_ = 0;
      winAttackCount_ = 0;
      loseAttackCount_ = 0;
      leftAttackCount_ = 0;
      threeStarWin_ = 0;
      twoStarWin_ = 0;
      oneStarWin_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClanNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClanIconBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, score_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, totalAttackCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, winAttackCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, loseAttackCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, leftAttackCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, threeStarWin_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, twoStarWin_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, oneStarWin_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClanNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClanIconBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, score_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalAttackCount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, winAttackCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, loseAttackCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, leftAttackCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, threeStarWin_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, twoStarWin_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, oneStarWin_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClanBattleStatisticsBeanVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsBeanVO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsBeanVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.class, com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.Builder.class);
      }

      // Construct using com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clanName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clanIcon_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        totalAttackCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        winAttackCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        loseAttackCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        leftAttackCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        threeStarWin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        twoStarWin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        oneStarWin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.internal_static_ClanBattleStatisticsBeanVO_descriptor;
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO getDefaultInstanceForType() {
        return com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance();
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO build() {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO buildPartial() {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO result = new com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clanName_ = clanName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clanIcon_ = clanIcon_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totalAttackCount_ = totalAttackCount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.winAttackCount_ = winAttackCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.loseAttackCount_ = loseAttackCount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.leftAttackCount_ = leftAttackCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.threeStarWin_ = threeStarWin_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.twoStarWin_ = twoStarWin_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.oneStarWin_ = oneStarWin_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO) {
          return mergeFrom((com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO other) {
        if (other == com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO.getDefaultInstance()) return this;
        if (other.hasClanName()) {
          bitField0_ |= 0x00000001;
          clanName_ = other.clanName_;
          onChanged();
        }
        if (other.hasClanIcon()) {
          bitField0_ |= 0x00000002;
          clanIcon_ = other.clanIcon_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasTotalAttackCount()) {
          setTotalAttackCount(other.getTotalAttackCount());
        }
        if (other.hasWinAttackCount()) {
          setWinAttackCount(other.getWinAttackCount());
        }
        if (other.hasLoseAttackCount()) {
          setLoseAttackCount(other.getLoseAttackCount());
        }
        if (other.hasLeftAttackCount()) {
          setLeftAttackCount(other.getLeftAttackCount());
        }
        if (other.hasThreeStarWin()) {
          setThreeStarWin(other.getThreeStarWin());
        }
        if (other.hasTwoStarWin()) {
          setTwoStarWin(other.getTwoStarWin());
        }
        if (other.hasOneStarWin()) {
          setOneStarWin(other.getOneStarWin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.vo.ClanBattleStatisticsVOProtocal.ClanBattleStatisticsBeanVO) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string clanName = 1;
      private java.lang.Object clanName_ = "";
      /**
       * <code>optional string clanName = 1;</code>
       */
      public boolean hasClanName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string clanName = 1;</code>
       */
      public java.lang.String getClanName() {
        java.lang.Object ref = clanName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clanName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clanName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClanNameBytes() {
        java.lang.Object ref = clanName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clanName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clanName = 1;</code>
       */
      public Builder setClanName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clanName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanName = 1;</code>
       */
      public Builder clearClanName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clanName_ = getDefaultInstance().getClanName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanName = 1;</code>
       */
      public Builder setClanNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clanName_ = value;
        onChanged();
        return this;
      }

      // optional string clanIcon = 2;
      private java.lang.Object clanIcon_ = "";
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasClanIcon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getClanIcon() {
        java.lang.Object ref = clanIcon_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clanIcon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClanIconBytes() {
        java.lang.Object ref = clanIcon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clanIcon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clanIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearClanIcon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clanIcon_ = getDefaultInstance().getClanIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clanIcon = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setClanIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clanIcon_ = value;
        onChanged();
        return this;
      }

      // optional int32 score = 3;
      private int score_ ;
      /**
       * <code>optional int32 score = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 score = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000004;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 3;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0;
        onChanged();
        return this;
      }

      // optional int32 totalAttackCount = 4;
      private int totalAttackCount_ ;
      /**
       * <code>optional int32 totalAttackCount = 4;</code>
       */
      public boolean hasTotalAttackCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 totalAttackCount = 4;</code>
       */
      public int getTotalAttackCount() {
        return totalAttackCount_;
      }
      /**
       * <code>optional int32 totalAttackCount = 4;</code>
       */
      public Builder setTotalAttackCount(int value) {
        bitField0_ |= 0x00000008;
        totalAttackCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalAttackCount = 4;</code>
       */
      public Builder clearTotalAttackCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalAttackCount_ = 0;
        onChanged();
        return this;
      }

      // optional int32 winAttackCount = 5;
      private int winAttackCount_ ;
      /**
       * <code>optional int32 winAttackCount = 5;</code>
       */
      public boolean hasWinAttackCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 winAttackCount = 5;</code>
       */
      public int getWinAttackCount() {
        return winAttackCount_;
      }
      /**
       * <code>optional int32 winAttackCount = 5;</code>
       */
      public Builder setWinAttackCount(int value) {
        bitField0_ |= 0x00000010;
        winAttackCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 winAttackCount = 5;</code>
       */
      public Builder clearWinAttackCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        winAttackCount_ = 0;
        onChanged();
        return this;
      }

      // optional int32 loseAttackCount = 6;
      private int loseAttackCount_ ;
      /**
       * <code>optional int32 loseAttackCount = 6;</code>
       */
      public boolean hasLoseAttackCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 loseAttackCount = 6;</code>
       */
      public int getLoseAttackCount() {
        return loseAttackCount_;
      }
      /**
       * <code>optional int32 loseAttackCount = 6;</code>
       */
      public Builder setLoseAttackCount(int value) {
        bitField0_ |= 0x00000020;
        loseAttackCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 loseAttackCount = 6;</code>
       */
      public Builder clearLoseAttackCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        loseAttackCount_ = 0;
        onChanged();
        return this;
      }

      // optional int32 leftAttackCount = 7;
      private int leftAttackCount_ ;
      /**
       * <code>optional int32 leftAttackCount = 7;</code>
       */
      public boolean hasLeftAttackCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 leftAttackCount = 7;</code>
       */
      public int getLeftAttackCount() {
        return leftAttackCount_;
      }
      /**
       * <code>optional int32 leftAttackCount = 7;</code>
       */
      public Builder setLeftAttackCount(int value) {
        bitField0_ |= 0x00000040;
        leftAttackCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leftAttackCount = 7;</code>
       */
      public Builder clearLeftAttackCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        leftAttackCount_ = 0;
        onChanged();
        return this;
      }

      // optional int32 threeStarWin = 8;
      private int threeStarWin_ ;
      /**
       * <code>optional int32 threeStarWin = 8;</code>
       */
      public boolean hasThreeStarWin() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 threeStarWin = 8;</code>
       */
      public int getThreeStarWin() {
        return threeStarWin_;
      }
      /**
       * <code>optional int32 threeStarWin = 8;</code>
       */
      public Builder setThreeStarWin(int value) {
        bitField0_ |= 0x00000080;
        threeStarWin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 threeStarWin = 8;</code>
       */
      public Builder clearThreeStarWin() {
        bitField0_ = (bitField0_ & ~0x00000080);
        threeStarWin_ = 0;
        onChanged();
        return this;
      }

      // optional int32 twoStarWin = 9;
      private int twoStarWin_ ;
      /**
       * <code>optional int32 twoStarWin = 9;</code>
       */
      public boolean hasTwoStarWin() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 twoStarWin = 9;</code>
       */
      public int getTwoStarWin() {
        return twoStarWin_;
      }
      /**
       * <code>optional int32 twoStarWin = 9;</code>
       */
      public Builder setTwoStarWin(int value) {
        bitField0_ |= 0x00000100;
        twoStarWin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 twoStarWin = 9;</code>
       */
      public Builder clearTwoStarWin() {
        bitField0_ = (bitField0_ & ~0x00000100);
        twoStarWin_ = 0;
        onChanged();
        return this;
      }

      // optional int32 oneStarWin = 10;
      private int oneStarWin_ ;
      /**
       * <code>optional int32 oneStarWin = 10;</code>
       */
      public boolean hasOneStarWin() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 oneStarWin = 10;</code>
       */
      public int getOneStarWin() {
        return oneStarWin_;
      }
      /**
       * <code>optional int32 oneStarWin = 10;</code>
       */
      public Builder setOneStarWin(int value) {
        bitField0_ |= 0x00000200;
        oneStarWin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 oneStarWin = 10;</code>
       */
      public Builder clearOneStarWin() {
        bitField0_ = (bitField0_ & ~0x00000200);
        oneStarWin_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClanBattleStatisticsBeanVO)
    }

    static {
      defaultInstance = new ClanBattleStatisticsBeanVO(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClanBattleStatisticsBeanVO)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanBattleStatisticsVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanBattleStatisticsVO_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClanBattleStatisticsBeanVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClanBattleStatisticsBeanVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ClanBattleStatisticsVO.proto\"s\n\026ClanBa" +
      "ttleStatisticsVO\022+\n\006attack\030\001 \001(\0132\033.ClanB" +
      "attleStatisticsBeanVO\022,\n\007defence\030\002 \001(\0132\033" +
      ".ClanBattleStatisticsBeanVO\"\361\001\n\032ClanBatt" +
      "leStatisticsBeanVO\022\020\n\010clanName\030\001 \001(\t\022\020\n\010" +
      "clanIcon\030\002 \001(\t\022\r\n\005score\030\003 \001(\005\022\030\n\020totalAt" +
      "tackCount\030\004 \001(\005\022\026\n\016winAttackCount\030\005 \001(\005\022" +
      "\027\n\017loseAttackCount\030\006 \001(\005\022\027\n\017leftAttackCo" +
      "unt\030\007 \001(\005\022\024\n\014threeStarWin\030\010 \001(\005\022\022\n\ntwoSt" +
      "arWin\030\t \001(\005\022\022\n\noneStarWin\030\n \001(\005BA\n\037com.p",
      "ureland.common.protocal.voB\036ClanBattleSt" +
      "atisticsVOProtocal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClanBattleStatisticsVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClanBattleStatisticsVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanBattleStatisticsVO_descriptor,
              new java.lang.String[] { "Attack", "Defence", });
          internal_static_ClanBattleStatisticsBeanVO_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ClanBattleStatisticsBeanVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClanBattleStatisticsBeanVO_descriptor,
              new java.lang.String[] { "ClanName", "ClanIcon", "Score", "TotalAttackCount", "WinAttackCount", "LoseAttackCount", "LeftAttackCount", "ThreeStarWin", "TwoStarWin", "OneStarWin", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
