// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyDB.proto

package com.pureland.common.protocal.db;

public final class ArmyDBProtocal {
  private ArmyDBProtocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ArmyDBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArmyDB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 playerId = 1;</code>
     */
    long getPlayerId();

    /**
     * <code>optional int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <code>optional int32 amount = 3;</code>
     */
    int getAmount();

    /**
     * <code>optional int32 exp = 4;</code>
     */
    int getExp();
  }
  /**
   * Protobuf type {@code ArmyDB}
   */
  public  static final class ArmyDB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ArmyDB)
      ArmyDBOrBuilder {
    // Use ArmyDB.newBuilder() to construct.
    private ArmyDB(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private ArmyDB() {
      playerId_ = 0L;
      cid_ = 0;
      amount_ = 0;
      exp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ArmyDB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 16: {

              cid_ = input.readInt32();
              break;
            }
            case 24: {

              amount_ = input.readInt32();
              break;
            }
            case 32: {

              exp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pureland.common.protocal.db.ArmyDBProtocal.internal_static_ArmyDB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pureland.common.protocal.db.ArmyDBProtocal.internal_static_ArmyDB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.class, com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.Builder.class);
    }

    public static final com.google.protobuf.Parser<ArmyDB> PARSER =
        new com.google.protobuf.AbstractParser<ArmyDB>() {
      public ArmyDB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArmyDB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ArmyDB> getParserForType() {
      return PARSER;
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <code>optional int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    /**
     * <code>optional int32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int EXP_FIELD_NUMBER = 4;
    private int exp_;
    /**
     * <code>optional int32 exp = 4;</code>
     */
    public int getExp() {
      return exp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (cid_ != 0) {
        output.writeInt32(2, cid_);
      }
      if (amount_ != 0) {
        output.writeInt32(3, amount_);
      }
      if (exp_ != 0) {
        output.writeInt32(4, exp_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (cid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, amount_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exp_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ArmyDB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArmyDB)
        com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pureland.common.protocal.db.ArmyDBProtocal.internal_static_ArmyDB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pureland.common.protocal.db.ArmyDBProtocal.internal_static_ArmyDB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.class, com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.Builder.class);
      }

      // Construct using com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        cid_ = 0;

        amount_ = 0;

        exp_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pureland.common.protocal.db.ArmyDBProtocal.internal_static_ArmyDB_descriptor;
      }

      public com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB getDefaultInstanceForType() {
        return com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.getDefaultInstance();
      }

      public com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB build() {
        com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB buildPartial() {
        com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB result = new com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB(this);
        result.playerId_ = playerId_;
        result.cid_ = cid_;
        result.amount_ = amount_;
        result.exp_ = exp_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB) {
          return mergeFrom((com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB other) {
        if (other == com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getCid() != 0) {
          setCid(other.getCid());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>optional int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>optional int32 cid = 2;</code>
       */
      public Builder setCid(int value) {
        
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cid = 2;</code>
       */
      public Builder clearCid() {
        
        cid_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>optional int32 amount = 3;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>optional int32 amount = 3;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 4;</code>
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ArmyDB)
    }

    // @@protoc_insertion_point(class_scope:ArmyDB)
    private static final com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB defaultInstance;static {
      defaultInstance = new com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB();
    }

    public static com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB getDefaultInstance() {
      return defaultInstance;
    }

    public com.pureland.common.protocal.db.ArmyDBProtocal.ArmyDB getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArmyDB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ArmyDB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ArmyDB.proto\"D\n\006ArmyDB\022\020\n\010playerId\030\001 \001" +
      "(\003\022\013\n\003cid\030\002 \001(\005\022\016\n\006amount\030\003 \001(\005\022\013\n\003exp\030\004" +
      " \001(\005B1\n\037com.pureland.common.protocal.dbB" +
      "\016ArmyDBProtocalb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ArmyDB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ArmyDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ArmyDB_descriptor,
        new java.lang.String[] { "PlayerId", "Cid", "Amount", "Exp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
